version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    tty: true 
    environment:
      - MYSQL_DATABASE=pessoadb
      - MYSQL_ROOT_PASSWORD=root 
    command: --innodb-use-native-aio=0 
    networks:
      - desafio-net

  node:
    container_name: node
    restart: always
    build: 
      context: ./node 
    networks:
     - desafio-net
    depends_on:
      - mysql

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    networks:
      - desafio-net
    ports:
     - '8080:80'
    depends_on:
      - node
      
networks:
  desafio-net:
    driver: bridge 

## sudo rm -rf volume
## docker image ls
## docker system prune -a